In [1]:
import torch
from torchvision import datasets, transforms
from PIL import Image
from resnet.net import *

files = [
    '/home/dl/sh_cv_robot/dataset/pic/light_red_green/test_image/211695194409_.pic.jpg', 
    # './test_image/221695194409_.pic.jpg', 
    # './test_image/231695194419_.pic.jpg', 
    # './test_image/241695194419_.pic.jpg'
]
label = [0, 0, 1, 1]
model = torch.load('/home/dl/sh_cv_robot/models/resnet50/light_red_green_clf.pt')
model.eval()
# model.to('cpu')
nonlinear = nn.Softmax(dim=1)
tfms = transforms.Compose([
    # transforms.ToTensor(),
    transforms.Resize(256),
    transforms.CenterCrop(256),
    transforms.ToTensor(),
    transforms.Normalize((0.485, 0.456, 0.406), (0.229, 0.224, 0.225))
])
res = []
for i, file in enumerate(files):
    image = Image.open(file).convert('RGB')
    sample = tfms(image) 
    output = nonlinear(model(sample.unsqueeze(0)))
    res = output.argmax().item()
    print(sample)
    print(output)
    print(res)
    # print(res == label[i])

tensor([[[0.4508, 0.4508, 0.4508,  ..., 0.3823, 0.3823, 0.3823],
         [0.4679, 0.4679, 0.4679,  ..., 0.3823, 0.3823, 0.3823],
         [0.4679, 0.4679, 0.4679,  ..., 0.3652, 0.3652, 0.3652],
         ...,
         [0.3481, 0.3481, 0.3481,  ..., 0.4851, 0.4851, 0.4851],
         [0.3481, 0.3481, 0.3481,  ..., 0.4851, 0.4851, 0.4851],
         [0.3481, 0.3481, 0.3481,  ..., 0.4851, 0.4851, 0.4851]],

        [[0.9580, 0.9580, 0.9580,  ..., 0.7304, 0.7304, 0.7304],
         [0.9580, 0.9580, 0.9580,  ..., 0.7304, 0.7304, 0.7304],
         [0.9755, 0.9755, 0.9755,  ..., 0.7129, 0.7129, 0.7129],
         ...,
         [0.5903, 0.5903, 0.5903,  ..., 0.7654, 0.7654, 0.7654],
         [0.5903, 0.5903, 0.5903,  ..., 0.7654, 0.7654, 0.7654],
         [0.5903, 0.5903, 0.5903,  ..., 0.7654, 0.7654, 0.7654]],

        [[0.8099, 0.8099, 0.8099,  ..., 0.6879, 0.6879, 0.6879],
         [0.8274, 0.8274, 0.8274,  ..., 0.6705, 0.6705, 0.6705],
         [0.8274, 0.8274, 0.8274,  ..., 0.6705, 0.6705, 0.

In [2]:
import PIL
PIL.__version__
import torchvision
torchvision.__version__

'0.15.1+cu117'

In [4]:
torch.__version__

'2.0.0+cu117'

In [3]:
import cv2
from PIL import Image
import numpy as np
arr1 = np.asarray(Image.open('/home/dl/sh_cv_robot/dataset/pic/light_red_green/test_image/211695194409_.pic.jpg')).astype('int64')
img = cv2.imread('/home/dl/sh_cv_robot/dataset/pic/light_red_green/test_image/211695194409_.pic.jpg', cv2.IMREAD_COLOR)
arr2 = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
print(np.amax(abs(arr1 - arr2)))

0


In [4]:
img = cv2.imread('/home/dl/sh_cv_robot/dataset/pic/light_red_green/test_image/211695194409_.pic.jpg')
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
print(tfms(Image.fromarray(img)))
print(tfms(Image.open('/home/dl/sh_cv_robot/dataset/pic/light_red_green/test_image/211695194409_.pic.jpg')))

tensor([[[0.4508, 0.4508, 0.4508,  ..., 0.3823, 0.3823, 0.3823],
         [0.4679, 0.4679, 0.4679,  ..., 0.3823, 0.3823, 0.3823],
         [0.4679, 0.4679, 0.4679,  ..., 0.3652, 0.3652, 0.3652],
         ...,
         [0.3481, 0.3481, 0.3481,  ..., 0.4851, 0.4851, 0.4851],
         [0.3481, 0.3481, 0.3481,  ..., 0.4851, 0.4851, 0.4851],
         [0.3481, 0.3481, 0.3481,  ..., 0.4851, 0.4851, 0.4851]],

        [[0.9580, 0.9580, 0.9580,  ..., 0.7304, 0.7304, 0.7304],
         [0.9580, 0.9580, 0.9580,  ..., 0.7304, 0.7304, 0.7304],
         [0.9755, 0.9755, 0.9755,  ..., 0.7129, 0.7129, 0.7129],
         ...,
         [0.5903, 0.5903, 0.5903,  ..., 0.7654, 0.7654, 0.7654],
         [0.5903, 0.5903, 0.5903,  ..., 0.7654, 0.7654, 0.7654],
         [0.5903, 0.5903, 0.5903,  ..., 0.7654, 0.7654, 0.7654]],

        [[0.8099, 0.8099, 0.8099,  ..., 0.6879, 0.6879, 0.6879],
         [0.8274, 0.8274, 0.8274,  ..., 0.6705, 0.6705, 0.6705],
         [0.8274, 0.8274, 0.8274,  ..., 0.6705, 0.6705, 0.

In [27]:
img = cv2.imread('/home/dl/sh_cv_robot/dataset/pic/light_red_green/test_image/211695194409_.pic.jpg')
import base64
def image2base64_new(img):
    _, im_arr = cv2.imencode('.jpg', img)  # im_arr: image in Numpy one-dim array format.
    # im_bytes = im_arr.tobytes()
    im_b64 = base64.b64encode(im_arr)
    return im_b64
print(image2base64_new(img))

b'/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAIBAQEBAQIBAQECAgICAgQDAgICAgUEBAMEBgUGBgYFBgYGBwkIBgcJBwYGCAsICQoKCgoKBggLDAsKDAkKCgr/2wBDAQICAgICAgUDAwUKBwYHCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgr/wAARCAAcABYDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwD638I/Bwa8IhGrrJO2yMCPJZm/2f4q83/bl/ZC8YeOPgjrXw705LmO6naNJNt61qsC7vmknX5mljVWZmj2/vPl2/3l+hfgj8R08Hatoni37PFNbWN2ovkbqIWXazD3Xdur6c/ac+Edr8TfhxceMfB8KtqkWns0Plj/AI+Y9u

In [5]:
from image_utils import image2base64, base642image,img_base64,base64_img,img_base64_new

In [8]:
img = Image.open('/home/dl/sh_cv_robot/dataset/pic/light_red_green/test_image/211695194409_.pic.jpg').convert('RGB')
img2 = base64_img(img_base64(img)).convert('RGB')
img2.save('/home/dl/sh_cv_robot/dataset/pic/light_red_green/test_image/211695194409_2.pic.png')

In [7]:
from PIL import ImageChops
diff = ImageChops.difference(img, img2)
if diff.getbbox():
    print("images are different")
else:
    print("images are the same")
if list(img.getdata()) == list(img2.getdata()):
    print("Identical")
else:
    print ("Different")




images are the same
Identical


In [9]:
print(tfms(img))
print(tfms(img2))

tensor([[[0.4508, 0.4508, 0.4508,  ..., 0.3823, 0.3823, 0.3823],
         [0.4679, 0.4679, 0.4679,  ..., 0.3823, 0.3823, 0.3823],
         [0.4679, 0.4679, 0.4679,  ..., 0.3652, 0.3652, 0.3652],
         ...,
         [0.3481, 0.3481, 0.3481,  ..., 0.4851, 0.4851, 0.4851],
         [0.3481, 0.3481, 0.3481,  ..., 0.4851, 0.4851, 0.4851],
         [0.3481, 0.3481, 0.3481,  ..., 0.4851, 0.4851, 0.4851]],

        [[0.9580, 0.9580, 0.9580,  ..., 0.7304, 0.7304, 0.7304],
         [0.9580, 0.9580, 0.9580,  ..., 0.7304, 0.7304, 0.7304],
         [0.9755, 0.9755, 0.9755,  ..., 0.7129, 0.7129, 0.7129],
         ...,
         [0.5903, 0.5903, 0.5903,  ..., 0.7654, 0.7654, 0.7654],
         [0.5903, 0.5903, 0.5903,  ..., 0.7654, 0.7654, 0.7654],
         [0.5903, 0.5903, 0.5903,  ..., 0.7654, 0.7654, 0.7654]],

        [[0.8099, 0.8099, 0.8099,  ..., 0.6879, 0.6879, 0.6879],
         [0.8274, 0.8274, 0.8274,  ..., 0.6705, 0.6705, 0.6705],
         [0.8274, 0.8274, 0.8274,  ..., 0.6705, 0.6705, 0.